### ISSUE TITLE
ald_demo has more production years than in should

### ISSUE THREAD

**Issue by georgeharris2deg** [RMI-PACTA/r2dii.data#240]
Within r2dii.data::ald_demo - the companies have production forecasts that go beyond the 5 years that in in the real ALD. 

The ALD demo should cover 7 years. (1 year historic, present year + 5 years forward-looking) 

Simplified example below 

expected  
r2dii.data::ald_demo
Company    Year    Production
A                 2019       5
A                 2020       5
A                 2021       5
A                 2022       6
A                 2023       7 
A                 2024       7
A                 2025       8 

Actual 
r2dii.data::ald_demo
Company    Year    Production
A                 2019       5
A                 2020       5
A                 2021       5
A                 2022       6
A                 2023       7 
A                 2024       7
A                 2025       8 
A                 2026       9 
A                 2027       9
A                 2028       9
etc.....

@jdhoffa @maurolepore @Antoine-Lalechere

**Comment by jdhoffa** [comment]
I am closing this, as I don't actually think it's an issue for a demo dataset to have a realistic range of years.
