### ISSUE TITLE
feat: `green_or_brown` gains scenario-level granularity

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/r2dii.data#246]
## Methodologically
If a 2-degree aligned scenario states that a technology should increase, we colloquially refer to it as "green", and associate to it a [sector-market share target](https://2degreesinvesting.github.io/r2dii.analysis/articles/target-market-share.html).

conversely, if the 2-degree aligned scenario states that this technology should decrease, we call it "brown", and associate to it a [technology-market share target](https://2degreesinvesting.github.io/r2dii.analysis/articles/target-market-share.html)

It is important to note, that these definitions are not necessarily consistent across scenarios. For example, the WEO2020 SDS scenario (which is a 2-degree aligned scenario) would have `nuclearcap` increasing (thus we would call it a "green" technology), however in the Net-Zero Asset Owners Alliance ISF 1.5 degree scenario, `nuclearcap` is set to decrease. 

## In practice
The static file `r2dii.data::green_or_brown` is used to dictate if a technology should increase or decrease: 

``` r
library(r2dii.data)

green_or_brown
#> # A tibble: 20 x 3
#>    sector       technology    green_or_brown
#>    <chr>        <chr>         <chr>         
#>  1 automotive   electric      green         
#>  2 automotive   hybrid        green         
#>  3 automotive   ice           brown         
#>  4 automotive   fuelcell      green         
#>  5 power        hydrocap      green         
#>  6 power        renewablescap green         
#>  7 power        coalcap       brown         
#>  8 power        gascap        brown         
#>  9 power        oilcap        brown         
#> 10 power        nuclearcap    green         
#> 11 oil and gas  oil           brown         
#> 12 oil and gas  gas           brown         
#> 13 coal         coal          brown         
#> 14 fossil fuels oil           brown         
#> 15 fossil fuels gas           brown         
#> 16 fossil fuels coal          brown         
#> 17 hdv          electric      green         
#> 18 hdv          hybrid        green         
#> 19 hdv          ice           brown         
#> 20 hdv          fuelcell      green
```

<sup>Created on 2021-07-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Using this file alone, would set a "green" target for `nuclearcap`, regardless of what scenario is used. 

## Solution

We either need to: 
a) Extend the file `green_or_brown` to include a column `source`, which dictates, per scenario, if the technology should increase or decrease

b) Calculate if the technology should increase or decrease programatically in `r2dii.analysis` (this would require the user to flag which scenario(s) are actually 2-degree aligned). 

My preference would be a), which is the more bulky/ time-consuming solution on our part, but relies on less, potentially confusing, input from the user 

[AB#10168](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/10168)

**Comment by AlexAxthelm** [comment]
@jdhoffa If I understand correctly, different scenarios have different definitions of green/brown techs. Does this mean that we would need one of these files for each scenario? And if so, what happens if a particular scenario doesn't comment on a particular tech? Do we have default fall-back positions?

This seems like an analyst/methodology question for now, and once that's decided, we can figure out what the best plan for implementation is.

**Comment by cjyetman** [comment]
> a) Extend the file green_or_brown to include a column source, which dictates, per scenario, if the technology should increase or decrease

this seems a bit wonky to me... if we let the scenario determine `green_or_brown` then there's no sense in maintaining a list of them which will need to be up to date and will break whenever a new scenario is added, when it could easily be inferred from the scenario data

> b) Calculate if the technology should increase or decrease programatically in r2dii.analysis (this would require the user to flag which scenario(s) are actually 2-degree aligned).

This has problems because whether a technology is increasing or decreasing in a given scenario is easily affected by what time horizon you're looking at, particularly because the default for PACTA is 5 years and the scenarios typical project far beyond that.

**Comment by jdhoffa** [comment]
@AlexAxthelm you understand mostly correctly, it isn't even really a definition per se, it's actually inferred directly from if the scenario increases or decreases production in a 2-degree aligned pathway. Let's take an example to see:

Consider the WEO 2020. It is a scenario provider, which contains a few different scenarios:

- Current Policies Scenario (CPS): Projects what will happen if all current policies proceed as expected (**NOT** 2-Degree Aligned)
- Stated Policies Scenario (SPS): Projects what will happen if all state policies proceed as expected (**NOT** 2-Degree Aligned)
- Sustainable Development Scenario (SDS): The only 2-Degree Aligned Scenario from the WEO. 

In principle, what we would do, is:

-  Take the 2-degree aligned scenario (in the example, the SDS) 
- Determine overall if production in any technology is increasing or decreasing, across it's ENTIRE time-horizon (all years for which the scenario projects production values)
- Label each technology as "increasing/ green" or "decreasing/ brown" 
- Apply targets accordingly

**Comment by jdhoffa** [comment]
> > a) Extend the file green_or_brown to include a column source, which dictates, per scenario, if the technology should increase or decrease
> 
> this seems a bit wonky to me... if we let the scenario determine `green_or_brown` then there's no sense in maintaining a list of them which will need to be up to date and will break whenever a new scenario is added, when it could easily be inferred from the scenario data
> 

I agree, except it isn't necessarily "easily" inferred from the scenario. As you point out later, it is very important that we: 
a) Include the entire time-horizon of the scenario
b) Determine the increasing/ decreasing flag ONLY from 2-degree aligned scenario. (In the example above, it doesn't matter if `renewablescap` is decreasing in the CPS, all that matters is what happens in the SDS)

From a user-perspective, there are a few solutions we could approach that would avoid us having to maintain the `green_or_brown` list: 
- Allow the user to manually specify which scenario is 2-degree aligned (per scenario source). This seems risky, and prone to mistakes
- Specify in the input `scenario` dataset which scenario is 2-degree aligned, and which isn't, and calculate increasing/ decreasing on the fly. This also seems risky to me, since if they happened to not input the full time-horizon of the scenario, they may miscalculate the flag. 
- Have an analyst determine if the technology is increasing or decreasing prior to shipping the `scenario` data, and include it as an extra column in the provided dataset. (This is basically just shifting the "maintenance onus" from `r2dii.data` to the scenario data preparation stage. 

As for option b), there are many reasons that I think this would be delicate/ prone to mistakes (as I somewhat outlined above)

**Comment by jdhoffa** [comment]
To be clear, I'm not exactly thrilled about any of these solutions, and happy for further input!

**Comment by AlexAxthelm** [comment]
I think option 3 (analysts make a determination) is the right call, but is this issue a blocker for the 2.0 release?

**Comment by jdhoffa** [comment]
It is a blocker for the inclusion of the NZAOA scenarios yes.

**Comment by AlexAxthelm** [comment]
Can we get analyst time to calculate the flags for that scenario for this release, and go back and include the other scenarios in later releases?

**Comment by jdhoffa** [comment]
Yes, I think we could add the column, calculate it for NZAOA, take the definition from that column (if it exists) and otherwise fallback to the green_or_brown definition for now. 

Not ideal, but I think it should work. And then we move towards deprecating green_or_brown, and having all definitions come from the column?

**Comment by jdhoffa** [comment]
An open question is if the scenarios have already been sent to users (without the column) for this release. I will clarify with George at 1pm

**Comment by maurolepore** [comment]
I'm only skimming -- sorry if this makes little sense.

@jdhoffa,

I sense one good solution is becomes less attractive because of maintenance costs. If so, can we engineer something to lower that cost? 

r2dii.data already refreshes all data/ by sourcing files in data-raw/ -- automatically on CI. 

1. Would it be possible to build some other script that solves this problem automatically for every commit? 
2. If so, is this the best solution of other solutions discussed above are better?

**Comment by jdhoffa** [comment]
Hey @maurolepore 

This is in principle a very good idea, however to fully automate this would require access to all of the actual scenario datasets, which is outside of the scope of `r2dii.data` (or it is for now at least).

**Comment by jdhoffa** [comment]
Need to assess this again, against 2022 scenarios

**Comment by jacobvjk** [comment]
If I understand this issue correctly, it is solved by https://github.com/RMI-PACTA/r2dii.analysis/issues/426

@jdhoffa

**Comment by jdhoffa** [comment]
Sounds good!
