### ISSUE TITLE
feat: `loanbook_demo` drops columns that are not crucial to `r2dii.analysis` functions

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/r2dii.data#257]
Relates to feedback from a bank. 
Since our data preparation guidance is to prepare input data exactly as `loanbook_demo`, we should either: 
* Keep all columns that are currently in `loanbook_demo`, but indicate which are actually crucial to `target_market_share` and `target_sda`
OR
* Remove the non-crucial columns

[AB#10167](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/10167)

**Comment by maurolepore** [comment]
Note we have [`r2dii.match::crucial_lbk()`](https://2degreesinvesting.github.io/r2dii.match/reference/crucial_lbk.html) but those are the minimum columns you need to run `r2dii.match::match_name()` -- it fails with `prioritize()` and thus with anything downstream.

Maybe we should modify `crucial_lbk()`?

``` r
library(dplyr, warn.conflicts = FALSE)
library(r2dii.data)
library(r2dii.match)

loanbook <- r2dii.data::loanbook_demo
ald <- r2dii.data::ald_demo

crucial_lbk()
#> [1] "id_ultimate_parent"                    
#> [2] "name_ultimate_parent"                  
#> [3] "id_direct_loantaker"                   
#> [4] "name_direct_loantaker"                 
#> [5] "sector_classification_system"          
#> [6] "sector_classification_direct_loantaker"

matched_crucial <- loanbook %>% 
  select(crucial_lbk()) %>% 
  match_name(ald)

try(prioritize(matched_crucial))
#> Error : Must have missing names:
#> `id_loan`
```

<sup>Created on 2021-09-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jacobvjk** [comment]
making this a priority so we can solve the connected issue #372 too
