### ISSUE TITLE
Complete `green_or_brown` to `increasing_or_decreasing` deprecation process

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/r2dii.data#307]

**Comment by cjyetman** [comment]
just a note... for folks that like to set nuclear as "brown", make sure this change in naming doesn't pass through to the user interface maybe

**Comment by jdhoffa** [comment]
Hmmm good point. 

Maybe `increasing_or_decreasing` is the way then

**Comment by jdhoffa** [comment]
Just thinking aloud at the potential issues, and things to consider to do this:
* From the perspective of `r2dii.data`, we likely want to offer a deprecation warning for one release, this will allow users to adapt their code from using `green_or_brown` to `increasing_or_decreasing`
* The dataset `green_or_brown` has a column called `green_or_brown` (in fact, even the dataset's contents reference the terms `green` and `brown`). Presumably, all of this should change. This means that, beyond just the name change, the dataset `increasing_or_decreasing` won't be a "direct stand-in" for `green_or_brown`
* This will have implications for `r2dii.analysis`, see: https://github.com/RMI-PACTA/r2dii.analysis/issues/434

**Comment by jdhoffa** [comment]
Leaving this issue open until we complete the deprecation process.
