### ISSUE TITLE
upkeep: `*_classification` files lose `code_level` column

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/r2dii.data#310]
I don't believe this is ever used. 

[AB#10170](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/10170)

**Comment by jdhoffa** [comment]
George and @jacobvjk have expressed (more or less) favour towards this.

**Comment by AlexAxthelm** [comment]
No problems from my side.
