### ISSUE TITLE
`macos-latest` check failing

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/r2dii.data#334]
Hard to tell if this is on our end, or something that will resolve itself. 
Making an issue to track it. 

See here: https://github.com/RMI-PACTA/r2dii.data/actions/runs/7818153068/job/21327688597?pr=333

**Comment by cjyetman** [comment]
I just re-ran it and it seems to be working now. Looks like it choked on downloading the r-lib action for some reason.
https://github.com/RMI-PACTA/r2dii.data/actions/runs/7818153068/job/21327960414?pr=333

**Comment by jdhoffa** [comment]
Sweet thanks man, closing
