### ISSUE TITLE
feat: `loanbook_demo` and `abcd_demo` have no non-NA values for `lei_direct_loantaker` or `lei` respectively

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/r2dii.data#349]
Expected behaviour:
At least one non-NA value for the `lei` relevant column.

Observed behaviour:
``` r
library(r2dii.data)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

nrow(dplyr::filter(loanbook_demo, !is.na(lei_direct_loantaker)))
#> [1] 0

nrow(dplyr::filter(abcd_demo, !is.na(lei)))
#> [1] 0
```

<sup>Created on 2024-03-06 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by jdhoffa** [comment]
Weirdly, the `lei` columns seem to have been removed purposefully in https://github.com/RMI-PACTA/r2dii.data/pull/316

@cjyetman any idea why this was done? The LEI calculating functionality produces entirely fake LEIs and adds them to a subset of entries. It is particularly critical now that https://github.com/RMI-PACTA/r2dii.match/pull/460 is merged.

**Comment by cjyetman** [comment]
> Weirdly, the `lei` columns seem to have been removed purposefully in #316
> 
> @cjyetman any idea why this was done? The LEI calculating functionality produces entirely fake LEIs and adds them to a subset of entries. It is particularly critical now that [RMI-PACTA/r2dii.match#460](https://github.com/RMI-PACTA/r2dii.match/pull/460) is merged.

Pretty sure I just started from https://github.com/RMI-PACTA/r2dii.data/blob/main/data-raw/loanbook_demo.csv and modified things to make it all fake... I guess I did not know to add LEIs to it.

**Comment by jdhoffa** [comment]
But that's the thing, the LEI's were already calculated, and then they were explicitly removed in this line:
https://github.com/RMI-PACTA/r2dii.data/blob/e57b1d3656c913510774820558e259d28074cdce/data-raw/abcd_demo.R#L197-L198

I was just curious if this was done intentionally/ why. But it sounds like there isn't a reason for it?

**Comment by cjyetman** [comment]
> But that's the thing, the LEI's were already calculated, and then they were explicitly removed in this line:
> 
> https://github.com/RMI-PACTA/r2dii.data/blob/e57b1d3656c913510774820558e259d28074cdce/data-raw/abcd_demo.R#L197-L198
> 
> I was just curious if this was done intentionally/ why. But it sounds like there isn't a reason for it?

hmmm.... now that you point that out, I vaguely remember this being a last minute request from George (to avoid sharing anything sensitive?). Maybe @jacobvjk or George would remember?

**Comment by jdhoffa** [comment]
Yeah, I had a feeling it was that. 

In any case, there is nothing sensitive since those values are calculated programatically/ randomly earlier on:
https://github.com/RMI-PACTA/r2dii.data/blob/e57b1d3656c913510774820558e259d28074cdce/data-raw/abcd_demo.R#L9-L37
