### ISSUE TITLE
feat: `gics_classification` has both 4-digit and 6-digit codes

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/r2dii.data#358]
Currently, `gics_classification` has both 4-digit and 6-digit codes. 

Since 6-digit is required to map to most PACTA sectors, I would suggest we only support that level of granularity (it seems disingenuous to offer 4-digit codes when we know they won't be sufficient for analysis in the end). 

(See how "construction materials" gets mapped to "cement")

Thoughts @jacobvjk ?

``` r
r2dii.data::gics_classification |> 
  dplyr::filter(nchar(code) == "6")
#> # A tibble: 68 × 4
#>    description                 code   sector       borderline
#>    <chr>                       <chr>  <chr>        <lgl>     
#>  1 energy equipment & services 101010 oil and gas  TRUE      
#>  2 oil, gas & consumable fuels 101020 oil and gas  FALSE     
#>  3 chemicals                   151010 not in scope FALSE     
#>  4 construction materials      151020 cement       TRUE      
#>  5 containers & packaging      151030 not in scope FALSE     
#>  6 metals & mining             151040 steel        TRUE      
#>  7 paper & forest products     151050 not in scope FALSE     
#>  8 aerospace & defense         201010 not in scope FALSE     
#>  9 building products           201020 cement       TRUE      
#> 10 construction & engineering  201030 not in scope FALSE     
#> # ℹ 58 more rows
```

<sup>Created on 2024-03-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by jacobvjk** [comment]
based on what I have seen, GICS has 8-digit codes for sub-industries. I would suggest including 6 and 8 digit codes. Even at 8 digits, GICS does not map neatly to PACTA sectors. We will have to live whit that.
https://www.msci.com/our-solutions/indexes/gics
https://www.spglobal.com/marketintelligence/en/documents/112727-gics-mapbook_2018_v3_letter_digitalspreads.pdf
