### ISSUE TITLE
upkeep: in `abcd_demo`, rename `abcd_timestamp` to `ald_timestamp`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/r2dii.data#372]
In #315 , the `abcd_demo` dataset had the `ald_timestamp` column renamed to `abcd_timestamp`. 

Unfortunately, the abcd data as Asset Impact distributes it still contains the name `ald_timestamp`. 

When pressed on this topic, Asset Impact was worried the breaking change of changing a column name might impact users existing workflows, and were hesitant to do so. 

We should align the column name with what is in the expected dataset. 

Alternatively, we could remove the column entirely (relates to #257 ), as I don't believe it is a critical column in any of the `pacta.*` or `r2dii.*` code:
https://github.com/search?q=org%3ARMI-PACTA%20ald_timestamp&type=code
https://github.com/search?q=org%3ARMI-PACTA+abcd_timestamp&type=code

FYI @jacobvjk

**Comment by jacobvjk** [comment]
I would almost opt to go for #257 and remove all the variables you identified as not crucial @jdhoffa. I think it is fair explain that other variables _can_ be added and what for. e.g. intermediate parent for the unlikely case that someone has this kind of ownership data. Or project finance flag for.. well what exactly? In the end, this is where it can be good to link to documentation explaining the new variable grouping of `pacta.multi.loanbook.*`

**Comment by jdhoffa** [comment]
I back it! Go for it
